### ISSUE TITLE
No Water

### ISSUE THREAD

**Issue by PeterDenton** [harmscho/NuTauSim#2]
When you turn water off something strange happens that I can't figure out. If I set the thickness to zero it seems to be fine, but if I also set the density to zero it returns zero events. The total grammage calculation is still correct. I am guessing that the problem is that dx is defined ~1/dens, but I am unclear on why that density is ever zero. Actually, I think I figured it out (it was my first guess but didn't work because of the below error). Replace the relevant line in include/Earth.cc with this one: "else if (R_meters <= (EARTHRADIUS - depth_new_layer_meters) ) dens = 2.6;" I just added an equal sign and that seems to do the trick.

Also, the makefile has an error. When you edit one of the included files (e.g. include/Earth.cc) it compiles that object file (include/Earth.o) but does not relink the main source file. To fix this one should change the relevant line to: "Simu_elost: Simu_elost.cxx $(OBJECTS)" or something.

**Comment by PeterDenton** [comment]
Additional comment, there should probably be an additional check if the density is zero in the step that calculates dx in the main code. I'm not sure what the use case would be (other than the goofy example I came across above) but it should be simple enough to implement something. For example, if (dens <1e-5) set dx based on the average density enroute which has already been calculated. Then if the average density is zero handle that as well.

**Comment by harmscho** [comment]
Thanks for pointing these things out. The latest commit fixed the `Makefile` and exists the program, while streaming a message to `std::cerr`,  when the user specifies non-physical parameters for the outer Earth layer.
