### ISSUE TITLE
Why do I get a different result from PHYSICAL REVIEW D 97, 023021 (2018)?

### ISSUE THREAD

**Issue by ntuphyalex** [harmscho/NuTauSim#3]
Hello. I am new to GitHub. I apologize for my nonprofessional comment.

I have used the example mentioned in README here to reproduce the figures in PHYSICAL REVIEW D 97, 023021 (2018), including the P_exitand E_tau. But I get a very different result.

P_exit 
(Blue: 10^19eV neutrino, Red: 10^18eV, Black: 10^17eV)
(Normal curve: from the phys. review D, dashed line: result from the example)
![1021_Prob_VS_emergemce_middle_ANITAcodeVSPaper](https://user-images.githubusercontent.com/56871111/67276872-21581c00-f4f8-11e9-9cef-ec01735c2363.png)

E_tau
(Blue: 10^19eV neutrino, Red: 10^18eV, Black: 10^17eV)
(Normal curve: from the phys. review D, Marker: result from the example)
![1021_EnVsEmergeAngle_ANITAcode_wError_CodeVSPaper](https://user-images.githubusercontent.com/56871111/67277011-7136e300-f4f8-11e9-87bc-a3b099d016e2.png)

I think I have implemented the right configuration (thickness of ice-layer, same cross section) . Please tell me if I have anything wrong.

**Comment by afromero** [comment]
Are you using the plots in the erratum? 
https://journals.aps.org/prd/abstract/10.1103/PhysRevD.99.069902

**Comment by ntuphyalex** [comment]
Yes, I think so. These graphs look the same as  the figures in the paper I downloaded.
Can you tell me where is the correct graph?

取得 Android 版 Outlook<https://aka.ms/ghei36>

________________________________

**Comment by ntuphyalex** [comment]
Sorry, no. I used the one published on January. However, the energy graph is still different from the plots in erratum because I don't see a suppression of Etau to 10^17.5eV in the result of my example run.

取得 Android 版 Outlook<https://aka.ms/ghei36>

________________________________

**Comment by afromero** [comment]
Ok, I assume you were able to reproduce the P_exit curves in the erratum.
Note that the red lines in Figure 6 of the erratum are the most probable energies (mode of the distribution), not the average. If you are calculating the average, that is likely the reason you are getting higher values.

**Comment by ntuphyalex** [comment]
Yes, I am using average value. In my own program, mean and mode are the same. I will try to calculate the mode of Etau again in your program.

取得 Android 版 Outlook<https://aka.ms/ghei36>

________________________________

**Comment by ntuphyalex** [comment]
I calculated the mode of E_tau with the result generated with your program and plotted a fig for initial E_nu = 10^19eV. But the result doesn't seem to be different. As you can see from my plot, the energy of tau doesn't go to 10^17.5 eV at about 1 deg. 

*Because in the erratum, the E_tau plot didn't change too much for emergence angle between 0.3 deg to 3 deg, I am still using the old plot of E_tau instead of the one in erratum.

![1024_EnVsEmergeAngle_ANITAcode_wError_CodeVSPaper_mode](https://user-images.githubusercontent.com/56871111/67450633-9d657780-f650-11e9-8aa6-20c8cd862837.png)
